name: Laravel API CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin123
          MYSQL_DATABASE: apirestful1
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env.testing
        run: cp .env.testing .env

      - name: Generate APP_KEY
        run: |
          php -r "file_exists('.env') || copy('.env.testing', '.env');"
          php artisan key:generate --show > key.txt
          KEY=$(cat key.txt)
          sed -i "s|APP_KEY=.*|APP_KEY=${KEY}|g" .env
          rm key.txt

      - name: Clear config cache
        run: php artisan config:clear

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
