name: Laravel API CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin123
          MYSQL_DATABASE: apirestful1
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Setup environment
        run: |
          # Copier le fichier d'exemple .env ou en créer un temporaire
          if [ -f .env.example ]; then
            cp .env.example .env
          else
            echo "APP_NAME=Laravel
            APP_ENV=testing
            APP_KEY=
            APP_DEBUG=true
            APP_URL=http://localhost
            DB_CONNECTION=mysql
            DB_HOST=127.0.0.1
            DB_PORT=3306
            DB_DATABASE=apirestful1
            DB_USERNAME=root
            DB_PASSWORD=admin123
            CACHE_DRIVER=array
            SESSION_DRIVER=array
            QUEUE_CONNECTION=sync" > .env
          fi

          # Générer la clé APP_KEY
          php artisan key:generate --ansi

          # Vider le cache de configuration
          php artisan config:clear

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
